<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="124" started-at="2016-03-03T08:46:33Z" finished-at="2016-03-03T08:46:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="124" started-at="2016-03-03T08:46:33Z" finished-at="2016-03-03T08:46:33Z">
      <class name="myTestCases.Hybrid_ExecuteTestCases_dataprovider">
        <test-method status="SKIP" signature="HybridExecuteClass(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:myTestCases.Hybrid_ExecuteTestCases_dataprovider@13efd49]" name="HybridExecuteClass" duration-ms="0" started-at="2016-03-03T14:16:33Z" data-provider="getData" finished-at="2016-03-03T14:16:33Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: /home/aarti/workspace/Hybrid driven Testing FrameworkSelenium/src/TestCase.xlsx (No such file or directory)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: /home/aarti/workspace/Hybrid driven Testing FrameworkSelenium/src/TestCase.xlsx (No such file or directory)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
Caused by: java.io.FileNotFoundException: /home/aarti/workspace/Hybrid driven Testing FrameworkSelenium/src/TestCase.xlsx (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at myExcelFileReader.ExcelReaderFile.ReadDataFromExcelFile(ExcelReaderFile.java:22)
	at myTestCases.Hybrid_ExecuteTestCases_dataprovider.dataProviderClass(Hybrid_ExecuteTestCases_dataprovider.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 20 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HybridExecuteClass -->
      </class> <!-- myTestCases.Hybrid_ExecuteTestCases_dataprovider -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
